### ISSUE TITLE
doesn't work with standard v13

### ISSUE THREAD

**Issue by khaledosman** [standard/vscode-standard#90]
- StandardJS version?
13.0.0
- VSCode version?
1.24.1 (1.24.1)
- StandardJS configuration?
default
- What do you have in the `OUTPUT` panel?
```
[Info  - 11:39:34] JavaScript Standard Style server is running.
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token ...
(node:13579) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): SyntaxError: Unexpected token ...
(node:13579) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): SyntaxError: Unexpected token ...
```

**Comment by khaledosman** [comment]
After updating my vscode to v1.36.1, I get
```
[Info  - 10:40:10 AM] JavaScript Standard Style library loaded from: /Users/khaledosman/Documents/github/my-project/node_modules/standard/index.js
[Error - 10:40:11 AM] 
Failed to load plugin 'react' declared in '--config » eslint-config-standard-jsx': Cannot find module 'eslint-plugin-react'
Require stack:
- /__placeholder__.js
Happend while validating /Users/khaledosman/Documents/github/my-project/lib/messaging.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in JavaScript Standard Style configuration.
2. If JavaScript Standard Style is installed globally, then make sure 'eslint-plugin-react' is installed globally as well.
3. If JavaScript Standard Style is installed locally, then 'eslint-plugin-react' isn't installed correctly.
```

Its a NodeJS azure functions repository, so there's no eslint or react stuff configured. only standard installed as a devDependency, and the cli works fine.

**Comment by khaledosman** [comment]
fixed by standard v13.0.2 https://github.com/standard/standard/blob/master/CHANGELOG.md#1302---2019-07-12
